name: StorageSign
main: wacky.storagesign.StorageSignCore
version: ${project.version}
author: wackyls6,sousi0125
api-version: 1.20
softdepend: [WorldGuard, Towny]
website: https://github.com/sousi0125/StorageSign
permissions:
    storagesign.*:
        description:
            children:
                storagesign.use: true
                storagesign.craft: true
                storagesign.place: true
                storagesign.break: true
                storagesign.create: true
                storagesign.autocollect: true
                storagesign.command.storagesign: true
                storagesign.command.storagesign.setsignamount: true
                storagesign.command.storagesign.setsignitem: true
                storagesign.command.storagesign.breakmode: true
    storagesign.use:
        description: Allows you to use a storagesign
        default: true
    storagesign.craft:
        description: Allows you to craft a storagesign
        default: true
    storagesign.place:
        description: Allows you to place a storagesign
        default: true
    storagesign.break:
        description: Allows you to break a storagesign
        default: true
    storagesign.create:
        description: Allows you to create a storagesign
        default: op
    storagesign.autocollect:
        description: Collect your picked items
        default: true
    storagesign.command.storagesign:
        description: Allows you to /storagesign command
        default: true
    storagesign.command.storagesign.setsignamount:
        description: Allows you to /storagesign setsignamount command
        default: op
    storagesign.command.storagesign.setsignitem:
        description: Allows you to /storagesign setsignitem command
        default: op
    storagesign.command.storagesign.breakmode:
        description: Allows you to /storagesign breakmode command
        default: true
commands:
    storagesign:
        aliases: [ss, storagesign]
        description: StorageSign Commands
        permission: storagesign.command.storagesign
        permission-message: §cNo Permission!
        usage: StorageSign
